---

- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/dev-env

  tasks:
    - name: Check sudo Password
      command: whoami
      become: yes
      become_method: sudo

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Tap Caskroom
      homebrew_tap: tap=caskroom/cask
      ignore_errors: yes

    - name: Install Docker for Mac
      homebrew_cask: name=docker state=present
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications

    - name: Create resolver directory
      file: path=/etc/resolver state=directory mode=0755
      become: yes
      become_method: sudo

    - name: Symlink .test resolver file at /etc/resolver/test
      file:
        src: "{{ dev_env_dir }}/ansible/resolver-test.conf"
        dest: /etc/resolver/test
        state: link
        force: yes
      become: yes
      become_method: sudo

    - name: Restart mDNSResponder
      command: killall -HUP mDNSResponder
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: Kill any running mDNSResponderHelper processes
      command: killall mDNSResponderHelper
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: Flush the DNS cache
      command: dscacheutil -flushcache
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: Symlink dev script in /usr/local/bin
      file:
        src: "{{ dev_env_dir }}/bin/dev"
        dest: /usr/local/bin/dev
        state: link
        force: yes

    - name: Ensure Docker for Mac is started
      command: open --background -a Docker

    - name: Ensure Docker for Mac container directory is excluded from Time Machine backups
      command: tmutil addexclusion -p /Users/{{ lookup('env','USER') }}/Library/Containers/com.docker.docker/Data/vms/0/Docker.raw
      become: yes
      become_method: sudo
      ignore_errors: yes
